### ISSUE TITLE
[TASKS] Bound Enhancements

### ISSUE THREAD

**Issue by Fusezion** [ShaneBeee/SkBee#400]
**Is your feature request related to a problem? Please describe.**
Bounds felt lonely as they never received Fusezion's touch. Source: Sleep Deprivation 

### **Tasks**
- [x] Add plural support for bound syntax
- [x] Add BoundEvent class and make ExitBoundEvent and EnterBoundEvent extend it
- [x] Rename bound events to BoundExitEvent and BoundEnterEvent respectfully
- [ ] Add bound parenting/children (Related #352)
- [ ] Add bound priority system (Related #352)
- [x] Add bound cloning/copying (Related #353)
- [x] *Optional* organize BoundConfig and Bound class into respective locations out of elements package
- [ ] *Optional* add a bound edit section for more seamless editing 
- [x] Fix bound edge cases like riding vehicles and entering vehicles

### **Additional context**
This Issue will simply be a task list containing anything related to any future bound updates that I plan to make when I finish, I've assigned myself to any current projects I have and will continue to add and monitor if anything new is needed.

**Comment by Fusezion** [comment]
Fixing soon laptop decided it will error and reset data

**Comment by Fusezion** [comment]
Closing this issue since all that's left is #352 which is fine left to it's own issue, no need for duplicates
