### ISSUE TITLE
[TASKS] Recipe Rework and Enhancements

### ISSUE THREAD

**Issue by Fusezion** [ShaneBeee/SkBee#418]
## **Is your feature request related to a problem? Please describe.**
This issue aims to provide a place to see what will be added/changing in recipes and give a glimpse into how it'll work. As time goes on task will be marked as completed.

### **Tasks**
- [x] Add PaperMC 1.18 PotionMix syntax
- [x] Replaced MaterialChoice with RecipeChoice
- [ ] Add ExprRecipeGroup, ExprRecipeID, ExprRecipeCategory, ExprRecipeShape
- [ ] Add more recipe events (SmithItemEvent included)
- [ ] ~~Add changes to the recipe expressions like group, result, category and such (Will not include ingredients or recipe shape)~~ ***NOT PLANNED ANYMORE***
- [ ] Add recipe class info for easier parity
  - Add delete changer for easy removal
- [x] Add support for 1.20 smithing recipes
- [x] Add advanced recipe section (2.7 only)
- [ ] See if I can combine EffKnowledgeBook into the recipe classinfo otherwise leave be
  - Deprecate EffKnowledgeBook in favor of a stored recipe expression
- [ ] Split remove and reset recipe methods into 2 class
  - Deprecate EffUnregisterRecipe in favor of delete changer on recipe classinfo
  - Move reset recipes into it's own separate effect

**Comment by Fusezion** [comment]
I want to try and get Recipe choice pr made tonight after work as that'll help speed up some of the rework task

**Comment by ShaneBeee** [comment]
closing due to inactivity, please re-open if you see fit
